[build]
    functions = "functions"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "https://permittree-prototype.netlify.app"
        Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
        Access-Control-Allow-Headers = "Content-Type, Authorization"
        Access-Control-Allow-Credentials = "true"
