[build]
    functions = "functions"

[[headers]]
  # Apply headers to all paths
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Origin = "https://permittree-prototype.netlify.app"
    Access-Control-Allow-Origin = "http://localhost:8888"